// nseSymbols.js
const nseSymbols = [
    "RELIANCE", 
    "TCS", 
    "INFY", 
    "HDFCBANK", 
    "ICICIBANK",
    "HINDUNILVR", 
    "LT", 
    "AXISBANK", 
    "SBIN", 
    "BAJFINANCE",
    "SAIL",
    "SJVN",
    "ITC",
    "BAJAJHFL",
    "TATAMOTORS",
    "UJJIVANSFB",
    "NFL",
    "NBCC",
    "FSL",
    "ASHOKLEY",
    "NHPC",
    "IOC",
    "BEL",
    "FSL",
    "CDSL",
    "GRSE",
    "NMDC",
    "SUZLON",
    "ADANIGREEN",
    "RTNPOWER",
    "DISHTV",
    "POWERGRID",
    "TTML",
    "ADANIENT",
    "AWL",
    "IRB",
    "ONGC",
    "RANASUG",
    "RPOWER",
    "RENUKA",
    "RAILTEL",
    "CESC",
    "JPPOWER",
    "MTNL",
    "ZAGGLE",
    "GRANULES",
    "TATATECH",
    "PNGJL",
    "NTPC","OREINTECH", "MAZDOCK","JSWINFRA","VEDL","SOUTHBANK", "ADANIPOWER", "BLS", "INDUSTOWER", "NMDC", "BAJAJCON","OLAELEC", "PNB", "IEX", "ZOMATO", "GAIL", "IRFC", "IRCTC", "ZENTEC", "NYKAA", "HAL", "IDEA", "LTF", "SPICEJET", "BHEL" ,"HCC", "HINDCOPPER", "TRIDENT", "NATIONALUM", "RVNL", "JIOFIN", "MOTHERSON", "TATASTEEL", "SCI", "IREDA", "PAYTM", "NAVINFLUOR", "PFC", "BPCL", "OLECTRA", "YESBANK" , "FEDERALBANK", "CENTRALBK", "MAHABANK", "CUB" ,"J&KBANK", "URJA", "UCOBANK", "WIPRO"   // Add more symbols as needed
];

export default nseSymbols;